# Generated by Django 5.1.1 on 2024-09-23 15:11

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country_of_origin",
            field=django_countries.fields.CountryField(
                default="GER", max_length=5, verbose_name="Country"
            ),
        ),
    ]
