# Generated by Django 5.1.1 on 2024-09-23 15:17

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_country_of_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country_of_origin",
            field=django_countries.fields.CountryField(
                default="DE", max_length=2, verbose_name="Country"
            ),
        ),
    ]
