# Generated by Django 5.1.1 on 2024-09-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_country_of_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("mason", "Mason"),
                    ("carpenter", "Carpenter"),
                    ("plumber", "Plumber"),
                    ("roofer", "Roofer"),
                    ("painter", "Painter"),
                    ("electrician", "Electrician"),
                    ("hvac", "Hvac"),
                    ("tenant", "Tenant"),
                ],
                default="tenant",
                max_length=20,
                verbose_name="Occupation",
            ),
        ),
    ]
